### ISSUE TITLE
Suggestions for additional collections

### ISSUE THREAD

**Issue by achamayou** [letmaik/meeting-backgrounds#3]
Bond: https://www.007.com/bond-backgrounds/
IWM: https://www.iwm.org.uk/history/download-a-video-call-background
Studio Ghibli: http://www.ghibli.jp/info/013251/
Met: https://www.metmuseum.org/blogs/collection-insights/2020/period-room-zoom-meeting-background

For the avoidance of doubt: I will PR, so long as the collections are acceptable :)

**Comment by letmaik** [comment]
Thanks!
Met and IWM are great, proper "empty" backgrounds. Ghibli looks fine, too, I'll leave it to you to judge as I don't have much connection to it. I find Bond a bit weak as it's a very small collection and two of them have people in them which is a bit weird as meeting background, but nevertheless, feel free to include it as well.
